@startmindmap tutorials
* tutorials
** beginners
*** 计划你的交易
**** 在交易之前，先制定你的计划，不要临时起意
***** 考虑因素
****** 何时入场
****** 止损
****** 止盈
****** 头寸（拒绝全仓梭哈）
****** 杠杆
****** 开仓理由（固定开仓理由，短线？蝙蝠？趋势？）
***** 确认开仓理由 -> 确认止盈、止损位置  -> 确认头寸规模，比如不损失1%、1‰（可以借助tradingview，确认头寸规模）
**** 重中之重
***** 交易是概率的游戏，止损和止盈，都是必须的
***** 先学习止损，在学习止盈
***** “截断亏损，让利润奔跑”，不适合新手，尤其是合约交易里
***** “及时止损，及时止盈”，指定这样的交易规则，完全意志贪婪与恐惧
***** 确保你设定了止损，以防止亏损扩大到你不能止损的地步
***** 正确的止损，不是亏损，只是交易的成本
**** 交易记录
***** 用excel表格，记录每一笔交易，入场价、止损价、止盈价、头寸、杠杆、开仓理由、以及最后是止盈还是止损
***** 交易记录，有利于事后复盘，且保证交易计划的执行
***** 它会让每一笔交易变的从容，减少胡乱开单
*** 风险优先的资金管理策略
**** 敬畏风险
***** 如果你想赢，就必须付出更多努力，忍受更多反人性的规则
***** 《幽灵的礼物》：交易是失败者的游戏，最善于输的人最终会赢
***** 当你开始某次交易时，不要把这次交易看成你所做的最后一次交易
***** 孤注一掷，是赌徒行为
***** 筹码分散，保证有能力进行很多次交易
***** 损失越小越好，认赔出场越快越好
**** 风险优先
***** 开仓前，算一下，打算会亏多少钱，会亏多少钱
***** 优先考虑风险，而不是收益
**** 大数法则
***** 抛硬币游戏，次数越多，越接近50%
***** 若一次定输赢，每次全仓，如果运气好，能迅速翻倍，但遇到一次猜测，就会全盘皆输
***** 成也重仓，败也重仓
**** 仓位导向/止损导向（推荐止损导向）
***** 每次打算损失多少
***** 新手建议每次损失0.5%（绝不超过1%）
**** 仓位一致
***** 如果使用同一种交易策略，则每次交易的止损空间，应该是大致相同的。这能保证仓位的一致。仓位，切忌忽大忽小。
**** 纪律的交易者
***** 没有纪律，规则形同虚设
***** 能够让你稳定盈利的，其实不是交易策略，也不只是有一套完整的交易规则，而是有严格执行如何交易规则的纪律
***** 果断止损
***** 与设止损，而非精神止损
***** 仓位过大，到了你输不起的地址，也容易出现情绪化止损
*** 日本蜡烛图技术
**** 为什么学？有什么用？
***** 识别反转信号
**** 怎么学
***** 《日本蜡烛图技术》\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/0-0.jpg{scale=0.4}>
**** 什么是蜡烛图
**** 蜡烛图的基础
***** 开盘价
***** 收盘价
***** 最高价
***** 最低价
***** 以上都是资金博弈、多空争夺的痕迹
**** 开盘价
***** 在传统股市，开盘价通常代表隔夜情绪，经过一夜的酝酿，各种利好利空新闻的投放，到了第二天开盘，人们迫不及待冲进市场，买入卖出，形成当天的开盘价
***** 开盘价往往能为当天的行情奠定基调
***** 如果盘口有缺失，也会形成强大的支撑阻力，时常被机构交易者所用
**** 收盘价
***** 比开盘价更重要，它是确认突破或跌破的关键
***** 比如，美股的日线收盘价，就代表投资者是否愿意持仓过夜的价格
***** 同样，在加密货币市场，收盘价，而不是插针的价格，更能表明市场情绪的变化
***** 确认突破？收盘价在重要阻力位以上，表明空头已无力打压，大概率继续上涨
***** 确认跌破？收盘价在重要支撑位一下，表明多头已无力抵抗，大概率继续下跌
***** 注意：时间级别，越大越有效
***** \n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/0-1.jpg{scale=0.4}>
**** 月线、周线、日线级别
***** 比特币也有开盘收盘，是以UTC格林威治时间计算的
***** 虽然没有休市的时候，但有经验的交易者也会参考这些重要的开盘收盘
***** 此外，大阳线、大阴线的开盘收盘价，交易者密集区被反复争夺的开盘收盘价，都有非常重要的支撑阻力作用
**** 反转形态
***** 单根K线形态
****** 纺锤线\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/1.jpg{scale=0.4}>
****** 风急浪大线（两头针）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/2.jpg{scale=0.4}>
****** 锤子线（底部反转信号）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/3.jpg{scale=0.4}>
****** 上吊线（顶部的危险信号，需要其他信号验证）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/4.jpg{scale=0.4}>
****** 流星线（顶部非常危险信号）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/5.jpg{scale=0.4}>
****** 倒锤子线（底部反转信号，需要其他信号验证）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/%E5%80%92%E9%94%A4%E5%AD%90%E7%BA%BF.jpg{scale=0.4}>
***** 危险的单根K线：十字线
****** 长腿十字线（多空均衡，原来的趋势告一段落\n底部十字线或者箱体内部的十字线一般不够成反转，\n但是可以用来验证价格区间、价格支撑和阻力）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6.jpg{scale=0.4}>
****** 蜻蜓十字线（阶段性底部信号或者狂热顶部）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7.jpg{scale=0.4}>
****** 墓碑十字线（顶部，表示下跌）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/8.jpg{scale=0.4}>
****** 北方十字线（通常机构出货）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/9.jpg{scale=0.4}>
****** 南方十字线（散户购买，不太重要）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/10.jpg{scale=0.4}>
***** 三星形态
****** 三星顶部形态和三星底部形态 \n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/8-18.jpg{scale=0.4}>
***** 强势反转的单根K线：捉腰带线
****** 看涨捉腰带线（跳空，低开直接往上收，比特币不常见）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/11.jpg{scale=0.4}>
****** 看跌捉腰带线（顶部开盘，减仓减仓，比特币不常见）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/12.jpg{scale=0.4}>
***** 多根K线的组合（强）
****** 看涨刺透（收盘的K线顶部超过前一根1/2，如果超过了一整根就是2B）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/13.jpg{scale=0.4}>
****** 乌云盖顶（和看涨刺透相反）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/14.jpg{scale=0.4}>
****** 看涨吞没（2B）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/15.jpg{scale=0.4}>
****** 看跌吞没（2B）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/16.jpg{scale=0.4}>
****** 看涨反击线（低开，收盘价几乎平齐，比特币市场不会出现）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/17.jpg{scale=0.4}>
****** 看跌反击线（高开，收盘价几乎平齐，比特币市场不会出现）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/18.jpg{scale=0.4}>
***** 孕线（弱）
****** 看跌孕线形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/19.jpg{scale=0.4}>
****** 看涨孕线形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/20.jpg{scale=0.4}>
****** 看跌十字孕线（反转概率更大一点）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/21.jpg{scale=0.4}>
****** 看涨十字孕线（反转概率更大一点）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/22.jpg{scale=0.4}>
***** 星线（比特币不太可能出现，严格讲是需要有一个跳空的行为存在）（强）
****** 启明星形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/23.jpg{scale=0.4}>
****** 黄昏星形态（及时没有跳空也需要注意了，当你用更小的时\n间周期看的时候就是一个头肩顶）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/24.jpg{scale=0.4}>
****** 十字启明星形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/25.jpg{scale=0.4}>
****** 十字黄昏星形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/26.jpg{scale=0.4}>
***** 平头（弱）
****** 双重顶或者双重底\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/27.jpg{scale=0.4}>
***** 三个黑乌鸦、红三兵（光头，反转形态，多单和空单离场点，不是开仓点）（强）
****** 三只黑乌鸦\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/28.jpg{scale=0.4}>
****** 红色三兵\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/29.jpg{scale=0.4}>
***** 三山形态和三川形态
****** 三山顶部形态（如果市场先后三次均从某一个高价位上回落下来，\n或者市场对某一个高价位向上进行了三次尝试，但都失败了，那么一个三山顶部形态就形成了。\n在三山顶部形态的最后一座山的最高点，\n还应当出现一种看跌的蜡烛图指标（比如说，一根十字线，或者一个乌云盖顶形态等），对三山顶部形态做出确认。）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-5.jpg{scale=0.4}>
****** 三尊顶部形态（三山顶部形态中，如果中间的山峰高于两侧的山峰））\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-36.jpg{scale=0.4}>
****** 三川底部形态（三山顶部形态的反面，在市场先后三度向下试探某个底部水平后，就形成了这类形态。\n市场必须向上突破这个底部形态的最高水平，才能证实底部过程已经完成）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-37.jpg{scale=0.4}>
****** 倒三尊形态 \n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-38.jpg{scale=0.4}>
***** 圆形顶部形态和平底锅底部形态（圆形底部形态）
****** 圆形顶部形态 \n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-51.jpg{scale=0.4}>
****** 圆形底部形态 \n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-52.jpg{scale=0.4}>
***** 塔形顶部形态和底部形态
****** 塔形顶部形态 （市场本来处在上升趋势中，在某一时刻，\n出现了一根坚挺的白色蜡烛线或者一系列白色蜡烛线，\n然后市场放缓了上涨的步调，\n接着出现了一根或者数根大的黑色蜡烛线，\n于是塔形顶部形态就完成）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-59.jpg{scale=0.4}>
****** 塔形底部形态（市场形成了一根或数根长长的黑色蜡烛线，\n表示空方动力丝毫不减。后来出现了几根小实体，\n缓和了行情看跌的气氛。最后出现了一根长长的白色蜡烛线，\n完成了一个塔形底部形态）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-60.jpg{scale=0.4}>
***** 窗口（比特币也不可能出现，窗口有强阻力或者支撑，盈亏比比较好，及时止损）
****** 上升窗口\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/30.jpg{scale=0.4}>
****** 下降窗口\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/31.jpg{scale=0.4}>
**** 持续形态
***** 窗口
****** 向上的窗口\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-1.jpg{scale=0.4}>
****** 向下的窗口\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-2.jpg{scale=0.4}>
***** 向上跳空和向下跳空并列阴阳线形态
****** 向上跳空阴阳线 （其中一根白色蜡烛线和一根黑色蜡烛\n线共同形成了一个向上的窗口。\n这根黑色蜡烛线的开市价位于前一个白色实体之内，\n收市价位于前一个白色实体之下。\n在这样的情况下，这根黑色蜡烛线的收市价，就构成了买卖双方争夺的要点。\n如果市场以收市价向下突破到该窗口之下，\n那么这个向上跳空并列阴阳线形态的看涨意义就不再成立了）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-10.jpg{scale=0.4}>
****** 向下跳空阴阳线\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-11.jpg{scale=0.4}>
****** 高价位跳空突破形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-13.jpg{scale=0.4}>
****** 低价位跳空突破形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-14.jpg{scale=0.4}>
****** 上升趋势中的向上跳空并列白色蜡烛线形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-18.jpg{scale=0.4}>
****** 下降趋势中的向下跳空并列白色蜡烛线形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-19.jpg{scale=0.4}>
***** 上升三法（上升三蜡烛线法）和下降三法（下降三蜡烛线法）形态
****** 上升三法形态（小实体可以是任意颜色，范围包含影线，\n一定要在第一根蜡烛之内，一定是小实体）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-21.jpg{scale=0.4}>
****** 下降三法形态（小实体可以是任意颜色，范围包含影线，\n一定要在第一根蜡烛之内，一定是小实体）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-22.jpg{scale=0.4}>
***** 分手线
****** 看涨和看跌分手线\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-31.jpg{scale=0.4}>
**** 化繁就简、重中之重
***** 关注实体大小
****** 实体逐渐变小，这说明之前的趋势逐渐失去动力
****** 实体逐渐变大，这说明之前的趋势愈来愈强，千万不要盲猜顶底
***** 工具、而非交易系统
****** 理论总是那么清晰，觉得学会了就可以马上赚钱，\n但到实际交易时，却不是这么回事。因为市场总是比案例更复杂。\n所以，蜡烛图技术可以是基本功，但不能应对一切走势，\n必须结合其他的技术分析指标一起使用。除了继续学习其他技术分支知识外，\n我们还可以考虑：选择蜡烛图有效性更高的市场去做交易。
**** 结合西方技术
***** 破低反涨形态与破高反跌形态\n 如果向下突破支撑水平的时候交易量较轻，\n随后向上反弹至最近跌破的支撑水平之上时交易量较重，\n就进一步增强了本形态的看涨意义。\n与之类似，在破高反跌形态中，如果向上突破阻挡水平时交易量较轻，\n随后回落至最近向上突破的阻挡水平之下时交易量较重，\n那么破高反跌形态成功的可能性也将进一步增加。\n破低反转或者破高反转之后可以将\n目标价格设置在之前最近的高点或者低点
****** <img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/11-11.jpg{scale=0.4}>
****** <img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/11-12.jpg{scale=0.4}>
*** 书
**** 《幽灵的礼物》
**** 《日本蜡烛图技术》
@endmindmap