@startmindmap tutorials
* tutorials
** 一、beginners
*** 计划你的交易
**** 在交易之前，先制定你的计划，不要临时起意
***** 考虑因素
****** 何时入场
****** 止损
****** 止盈
****** 头寸（拒绝全仓梭哈）
****** 杠杆
****** 开仓理由（固定开仓理由，短线？蝙蝠？趋势？）
***** 确认开仓理由 -> 确认止盈、止损位置  -> 确认头寸规模，比如不损失1%、1‰（可以借助tradingview，确认头寸规模）
**** 重中之重
***** 交易是概率的游戏，止损和止盈，都是必须的
***** 先学习止损，在学习止盈
***** “截断亏损，让利润奔跑”，不适合新手，尤其是合约交易里
***** “及时止损，及时止盈”，指定这样的交易规则，完全意志贪婪与恐惧
***** 确保你设定了止损，以防止亏损扩大到你不能止损的地步
***** 正确的止损，不是亏损，只是交易的成本
**** 交易记录
***** 用excel表格，记录每一笔交易，入场价、止损价、止盈价、头寸、杠杆、开仓理由、以及最后是止盈还是止损
***** 交易记录，有利于事后复盘，且保证交易计划的执行
***** 它会让每一笔交易变的从容，减少胡乱开单
*** 风险优先的资金管理策略
**** 敬畏风险
***** 如果你想赢，就必须付出更多努力，忍受更多反人性的规则
***** 《幽灵的礼物》：交易是失败者的游戏，最善于输的人最终会赢
***** 当你开始某次交易时，不要把这次交易看成你所做的最后一次交易
***** 孤注一掷，是赌徒行为
***** 筹码分散，保证有能力进行很多次交易
***** 损失越小越好，认赔出场越快越好
**** 风险优先
***** 开仓前，算一下，打算会亏多少钱，会亏多少钱
***** 优先考虑风险，而不是收益
**** 大数法则
***** 抛硬币游戏，次数越多，越接近50%
***** 若一次定输赢，每次全仓，如果运气好，能迅速翻倍，但遇到一次猜测，就会全盘皆输
***** 成也重仓，败也重仓
**** 仓位导向/止损导向（推荐止损导向）
***** 每次打算损失多少
***** 新手建议每次损失0.5%（绝不超过1%）
**** 仓位一致
***** 如果使用同一种交易策略，则每次交易的止损空间，应该是大致相同的。这能保证仓位的一致。仓位，切忌忽大忽小。
**** 纪律的交易者
***** 没有纪律，规则形同虚设
***** 能够让你稳定盈利的，其实不是交易策略，也不只是有一套完整的交易规则，而是有严格执行如何交易规则的纪律
***** 果断止损
***** 与设止损，而非精神止损
***** 仓位过大，到了你输不起的地址，也容易出现情绪化止损
*** 日本蜡烛图技术
**** 为什么学？有什么用？
***** 识别反转信号
**** 怎么学
***** 《日本蜡烛图技术》\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/0-0.jpg{scale=0.4}>
**** 什么是蜡烛图
**** 蜡烛图的基础
***** 开盘价
***** 收盘价
***** 最高价
***** 最低价
***** 以上都是资金博弈、多空争夺的痕迹
**** 开盘价
***** 在传统股市，开盘价通常代表隔夜情绪，经过一夜的酝酿，各种利好利空新闻的投放，到了第二天开盘，人们迫不及待冲进市场，买入卖出，形成当天的开盘价
***** 开盘价往往能为当天的行情奠定基调
***** 如果盘口有缺失，也会形成强大的支撑阻力，时常被机构交易者所用
**** 收盘价
***** 比开盘价更重要，它是确认突破或跌破的关键
***** 比如，美股的日线收盘价，就代表投资者是否愿意持仓过夜的价格
***** 同样，在加密货币市场，收盘价，而不是插针的价格，更能表明市场情绪的变化
***** 确认突破？收盘价在重要阻力位以上，表明空头已无力打压，大概率继续上涨
***** 确认跌破？收盘价在重要支撑位一下，表明多头已无力抵抗，大概率继续下跌
***** 注意：时间级别，越大越有效
***** \n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/0-1.jpg{scale=0.4}>
**** 月线、周线、日线级别
***** 比特币也有开盘收盘，是以UTC格林威治时间计算的
***** 虽然没有休市的时候，但有经验的交易者也会参考这些重要的开盘收盘
***** 此外，大阳线、大阴线的开盘收盘价，交易者密集区被反复争夺的开盘收盘价，都有非常重要的支撑阻力作用
**** 反转形态
***** 单根K线形态
****** 纺锤线\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/1.jpg{scale=0.4}>
****** 风急浪大线（两头针）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/2.jpg{scale=0.4}>
****** 锤子线（底部反转信号）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/3.jpg{scale=0.4}>
****** 上吊线（顶部的危险信号，需要其他信号验证）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/4.jpg{scale=0.4}>
****** 流星线（顶部非常危险信号）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/5.jpg{scale=0.4}>
****** 倒锤子线（底部反转信号，需要其他信号验证）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/%E5%80%92%E9%94%A4%E5%AD%90%E7%BA%BF.jpg{scale=0.4}>
***** 危险的单根K线：十字线
****** 长腿十字线（多空均衡，原来的趋势告一段落\n底部十字线或者箱体内部的十字线一般不够成反转，\n但是可以用来验证价格区间、价格支撑和阻力）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6.jpg{scale=0.4}>
****** 蜻蜓十字线（阶段性底部信号或者狂热顶部）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7.jpg{scale=0.4}>
****** 墓碑十字线（顶部，表示下跌）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/8.jpg{scale=0.4}>
****** 北方十字线（通常机构出货）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/9.jpg{scale=0.4}>
****** 南方十字线（散户购买，不太重要）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/10.jpg{scale=0.4}>
***** 三星形态
****** 三星顶部形态和三星底部形态 \n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/8-18.jpg{scale=0.4}>
***** 强势反转的单根K线：捉腰带线
****** 看涨捉腰带线（跳空，低开直接往上收，比特币不常见）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/11.jpg{scale=0.4}>
****** 看跌捉腰带线（顶部开盘，减仓减仓，比特币不常见）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/12.jpg{scale=0.4}>
***** 多根K线的组合（强）
****** 看涨刺透（收盘的K线顶部超过前一根1/2，如果超过了一整根就是2B）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/13.jpg{scale=0.4}>
****** 乌云盖顶（和看涨刺透相反）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/14.jpg{scale=0.4}>
****** 看涨吞没（2B）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/15.jpg{scale=0.4}>
****** 看跌吞没（2B）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/16.jpg{scale=0.4}>
****** 看涨反击线（低开，收盘价几乎平齐，比特币市场不会出现）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/17.jpg{scale=0.4}>
****** 看跌反击线（高开，收盘价几乎平齐，比特币市场不会出现）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/18.jpg{scale=0.4}>
***** 孕线（弱）
****** 看跌孕线形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/19.jpg{scale=0.4}>
****** 看涨孕线形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/20.jpg{scale=0.4}>
****** 看跌十字孕线（反转概率更大一点）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/21.jpg{scale=0.4}>
****** 看涨十字孕线（反转概率更大一点）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/22.jpg{scale=0.4}>
***** 星线（比特币不太可能出现，严格讲是需要有一个跳空的行为存在）（强）
****** 启明星形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/23.jpg{scale=0.4}>
****** 黄昏星形态（及时没有跳空也需要注意了，当你用更小的时\n间周期看的时候就是一个头肩顶）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/24.jpg{scale=0.4}>
****** 十字启明星形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/25.jpg{scale=0.4}>
****** 十字黄昏星形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/26.jpg{scale=0.4}>
***** 平头（弱）
****** 双重顶或者双重底\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/27.jpg{scale=0.4}>
***** 三个黑乌鸦、红三兵（光头，反转形态，多单和空单离场点，不是开仓点）（强）
****** 三只黑乌鸦\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/28.jpg{scale=0.4}>
****** 红色三兵\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/29.jpg{scale=0.4}>
***** 三山形态和三川形态
****** 三山顶部形态（如果市场先后三次均从某一个高价位上回落下来，\n或者市场对某一个高价位向上进行了三次尝试，但都失败了，那么一个三山顶部形态就形成了。\n在三山顶部形态的最后一座山的最高点，\n还应当出现一种看跌的蜡烛图指标（比如说，一根十字线，或者一个乌云盖顶形态等），对三山顶部形态做出确认。）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-5.jpg{scale=0.4}>
****** 三尊顶部形态（三山顶部形态中，如果中间的山峰高于两侧的山峰））\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-36.jpg{scale=0.4}>
****** 三川底部形态（三山顶部形态的反面，在市场先后三度向下试探某个底部水平后，就形成了这类形态。\n市场必须向上突破这个底部形态的最高水平，才能证实底部过程已经完成）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-37.jpg{scale=0.4}>
****** 倒三尊形态 \n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-38.jpg{scale=0.4}>
***** 圆形顶部形态和平底锅底部形态（圆形底部形态）
****** 圆形顶部形态 \n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-51.jpg{scale=0.4}>
****** 圆形底部形态 \n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-52.jpg{scale=0.4}>
***** 塔形顶部形态和底部形态
****** 塔形顶部形态 （市场本来处在上升趋势中，在某一时刻，\n出现了一根坚挺的白色蜡烛线或者一系列白色蜡烛线，\n然后市场放缓了上涨的步调，\n接着出现了一根或者数根大的黑色蜡烛线，\n于是塔形顶部形态就完成）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-59.jpg{scale=0.4}>
****** 塔形底部形态（市场形成了一根或数根长长的黑色蜡烛线，\n表示空方动力丝毫不减。后来出现了几根小实体，\n缓和了行情看跌的气氛。最后出现了一根长长的白色蜡烛线，\n完成了一个塔形底部形态）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/6-60.jpg{scale=0.4}>
***** 窗口（比特币也不可能出现，窗口有强阻力或者支撑，盈亏比比较好，及时止损）
****** 上升窗口\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/30.jpg{scale=0.4}>
****** 下降窗口\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/31.jpg{scale=0.4}>
**** 持续形态
***** 窗口
****** 向上的窗口\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-1.jpg{scale=0.4}>
****** 向下的窗口\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-2.jpg{scale=0.4}>
***** 向上跳空和向下跳空并列阴阳线形态
****** 向上跳空阴阳线 （其中一根白色蜡烛线和一根黑色蜡烛\n线共同形成了一个向上的窗口。\n这根黑色蜡烛线的开市价位于前一个白色实体之内，\n收市价位于前一个白色实体之下。\n在这样的情况下，这根黑色蜡烛线的收市价，就构成了买卖双方争夺的要点。\n如果市场以收市价向下突破到该窗口之下，\n那么这个向上跳空并列阴阳线形态的看涨意义就不再成立了）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-10.jpg{scale=0.4}>
****** 向下跳空阴阳线\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-11.jpg{scale=0.4}>
****** 高价位跳空突破形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-13.jpg{scale=0.4}>
****** 低价位跳空突破形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-14.jpg{scale=0.4}>
****** 上升趋势中的向上跳空并列白色蜡烛线形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-18.jpg{scale=0.4}>
****** 下降趋势中的向下跳空并列白色蜡烛线形态\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-19.jpg{scale=0.4}>
***** 上升三法（上升三蜡烛线法）和下降三法（下降三蜡烛线法）形态
****** 上升三法形态（小实体可以是任意颜色，范围包含影线，\n一定要在第一根蜡烛之内，一定是小实体）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-21.jpg{scale=0.4}>
****** 下降三法形态（小实体可以是任意颜色，范围包含影线，\n一定要在第一根蜡烛之内，一定是小实体）\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-22.jpg{scale=0.4}>
***** 分手线
****** 看涨和看跌分手线\n\n<img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/7-31.jpg{scale=0.4}>
**** 化繁就简、重中之重
***** 关注实体大小
****** 实体逐渐变小，这说明之前的趋势逐渐失去动力
****** 实体逐渐变大，这说明之前的趋势愈来愈强，千万不要盲猜顶底
***** 工具、而非交易系统
****** 理论总是那么清晰，觉得学会了就可以马上赚钱，\n但到实际交易时，却不是这么回事。因为市场总是比案例更复杂。\n所以，蜡烛图技术可以是基本功，但不能应对一切走势，\n必须结合其他的技术分析指标一起使用。除了继续学习其他技术分支知识外，\n我们还可以考虑：选择蜡烛图有效性更高的市场去做交易。
**** 结合西方技术
***** 破低反涨形态与破高反跌形态\n 如果向下突破支撑水平的时候交易量较轻，\n随后向上反弹至最近跌破的支撑水平之上时交易量较重，\n就进一步增强了本形态的看涨意义。\n与之类似，在破高反跌形态中，如果向上突破阻挡水平时交易量较轻，\n随后回落至最近向上突破的阻挡水平之下时交易量较重，\n那么破高反跌形态成功的可能性也将进一步增加。\n破低反转或者破高反转之后可以将\n目标价格设置在之前最近的高点或者低点
****** <img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/11-11.jpg{scale=0.4}>
****** <img::https://cdn.jsdelivr.net/gh/leiiiooo/Doccod/images/tia/basic/candlestick/11-12.jpg{scale=0.4}>
*** 书
**** 《幽灵的礼物》
**** 《日本蜡烛图技术》
** 二、道氏理论（趋势，右侧）
*** 导论
**** 平均价格包容消化一切因素（道琼斯指数等相关指数由来）
**** 市场具有三种趋势（主要趋势月线，次要趋势周线，微观趋势日常波动，短线交易者关注比如日线，不同的时间级别走向不同，不同级别提早做出预案，每周，每月）
**** 大趋势分为三个阶段（比如像后来的波浪理论，参考此，5浪，3个上升浪）
**** 各种平均价格必须相互验证（例如：纳指和道指相互验证，例如各大指数都好，可能来一波小牛市 ）
**** 交易量必须验证趋势（量增价涨）
**** 除非有明确反转信号，我们才能判 定现有趋势已经完结（）
**** 优势
***** 趋势跟随
***** 如果有大的趋势行情，通常不会错过
***** 大牛市、大熊市，非常好用
***** 开山始祖，后市的很多交易法都溯源于此
**** 不足
***** 右侧交易法，有一定延后性，不能埋在最低点，不能埋在最高点。必须是大牛市、大熊市，有较长的趋势行情才行。
***** 趋势行情不常用，盘整行情中，容易磨损本金
***** 突破开仓的交易法，在大牛市很好用，使用的人非常多。但在没有趋势的时候，就是非常拥挤的交易，有一些短线策略就是专门做反突破的。
*** 支撑与阻力
**** 支撑位（潜在买盘的水平价位）阻力（潜在卖盘的水平价位）
**** 趋势
***** 低点、高点逐渐升高（日线、周线高点不再升高一定需要留意这种情况），如果不能创出更高的低点，相同或者更低，接下来行情可能反转
**** 密集区
***** 交易密集区，代表着大量而充分的多空换手
***** 多头希望跌下来，加仓
***** 空头希望跌下来，成本离场
***** 合力之下，变成强有力的支撑或阻力
**** 估算
***** 市场在此处停留的时间
***** 交易量
***** 交易活动的发生时间距当前的远近
***** 离开成本区后的距离
**** 痛感
***** 如果曾经离开交易区越远，支撑阻力的作用将会越大
****** 对多头，离开开仓价越远，尝到了甜头，跌回开仓价附近。再次加仓
****** 空头，巨大浮亏，跌回，平单
***** 如果价格离开成本区不远，多头没那么贪婪不会加仓，空头也不恐惧不会平仓。这就是为什么突破之后，最好在量增价涨的情况下，远离成本去，这样的回踩、回抽才能有效
***** 留意1.13假突破
**** 整数
***** 如果突破历史前高，或者和之前的价格相距很远，那么，通常的支撑阻力就将失去意义，而整数位就会变得值得关注
*** 趋势线
**** 画法
***** 两点成线
***** 三点确认
***** 大多数情况，包含影线，因为趋势线应描述全部的价格变化
***** 大时间周期，使用对数坐标
**** 重要程度
***** 持续时间
***** 被测试的次数
***** 被关注的程度
**** 支阻互换
***** 倾斜意义的支阻互换，重要性不如水平位置
**** 扇形突破
**** 百分比回撤
***** 0.382 0.33 0.618 0.66
**** 速度阻力线（很重要）
***** 0.25（江恩认为的重要数字）0.382 0.5 0.618 0.786
*** 反转形态
**** 前提
***** 原本就存在趋势
***** 趋势线突破，第一信号
***** 形态的持续时间越长，规模越大，随之而来的反转动作越大
***** 底部时间较长，且波动性小
***** 顶部时间较短，波动性大
***** 交易量，是趋势反转的最好验证
**** 常见
***** 头肩顶
****** 一定是在趋势中
****** 左肩伴随较大的成交量
****** 以相对较小的成交量完成头部
****** 随后的回调跌破左肩的高点，且接近左肩的底部
****** 右肩的成交量明显减弱，且常在1/2和2/3处受阻
****** 收盘价低于颈线，甚至低于头部的左 侧低点
****** 跌破后，百分比确认、双日确认
****** 跌破颈线后，经常反抽测试，若跌破时有巨量，表明势力较强，不反抽或弱反抽
****** 跌破反抽
******* 跌破时，成交量大
******* 反抽时，成交量低
******* 反抽后继续下跌，成交量大
****** 特殊情况
******* 若颈线未跌破，则不可预判跌破。颈线未跌破时，是强支撑
******* 若颈线跌破后，又回抽上了颈线，表明趋势仍未衰竭，可能继续向上。空单止损。
******* 这种假突破，通常不做反转趋势，因市场构造已明显改变
****** 目标测算
******* 头到颈线的垂直距离
******* 头到颈线的右半部分
******* 这知识最近目标，通常会更远
***** 头肩底
****** 从左到右，交易量逐渐递增
****** 底部向上突破的时候，通常带有较大的成交量（下跌时，价格因自重而下跌）
****** 突破后，通常会有回抽，最好成交量较小
***** 颈线的倾斜程度
****** 如果顶部时，市场较为疲弱，颈线会向下倾斜，如果等跌破后，在开仓做空，就延误了时机
****** 如果底部时，市场较为强势，颈线会向上倾斜，如果等突破后，在开仓做多，就延误了时机
****** 所以，在做右肩的时候，就可在趋势线跌破/突破时介入
****** 或到左肩相同位置，或到斐波那契位，或突破后回抽/回踩，都是不错的介入时机
***** 时间
****** 不管是双重顶、双重底，还是牛市陷阱、熊市陷阱，两个高点或者两个低点之间的时间很重要。如果酝酿时间越长，第二次的受阻或者假突破，带来的反向作用力越大
****** 如果酝酿第二次高点的时间太短，很可能只是通道或者假信号
*** 持续形态
**** 在趋势行情中
**** 三角形
***** 四个点
***** 两条线
***** 和楔形的区别，三角形是方向不同的两条线，楔形是方向相同的两条线，只不过一条快一点，一条慢一点
***** 对称三角形（中性，顺势）、上升三角形（顶部是水平，通常看涨）、下降三角形（底部是水平，通常看跌）
***** 数浪
****** 上下各有两个点后，可开始考虑，是不是要出现三角形
****** 第五个点尤其值得关注，它配合成交量、斐波那契、中轴等
****** 第六个点，通常是三角形内的最后点，因为六点形成五浪。（仅有理论意义，没有实战价值）
***** 时间
****** 通常来说，三角形盘整，到3/4时，就一定要出方向
****** 如果超过3/4还没有出方向，可能有两种情况：1、假突破，不要做，也就是说，只要在行情末尾，不管真假突破，都不要做。2、无序盘整，横着走
****** 可用肉眼看进度，也可用斐波那契时间来预测大致的突破时间（0，0.382，0.5，0.618，0.75）
***** 假突破
****** 真突破，指的是，收盘价的确认突破，而不是插针突破
****** 如果在三角形的后1/4，不管真假突破，最好都不要做
****** 如果在三进行的前3/4，最好前2/3，假突破且带量，收回三角形后，可做反向
****** 进场被机构利用，形成熊市陷阱、牛市陷阱，机构如果建仓，之后行情通常不小
***** 交易量
****** 三角形内，通常是缩量的，直到快出方向的时候
****** 你可以在四次触点之后，留意成交量的变化
****** 向上突破时，必须有成交量的配置
****** 向下跌破时，现货不必有大成交量，但合约最好还是有成交量来确认
****** 假突破/跌破时，有巨大成交量，是可遇不可求的
***** 测算
****** 三角形最长边。入口的长边，调整下方向，从突破点画起。tp1
****** 三角形的对称线。平移突破的另一条边，画出。tp2
****** 盘整区之前的走势。原来趋势，到三角入口，平移。tp3
@endmindmap